version: "3"
   
services:

  # MySQL Database
  db:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      # - MYSQL_HOST=localhost
      - MYSQL_DATABASE=core
      # - MYSQL_USER=user
      # - MYSQL_PASSWORD=123
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=123
      # - MYSQL_ALLOW_EMPTY_PASSWORD=1

  # backend API with Django
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
        sh -c "sleep 10 &&
              python manage.py migrate &&
              python manage.py populateDB &&
              python manage.py runserver 0.0.0.0:8000
              "
    # volumes:
    #   - .:/app/backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  # frontend app with React js
  frontend:
    command : npm start
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # volumes:
    #   - .:/app/frontend
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend
      - db


